# Generated by Django 3.1.6 on 2024-05-10 19:14

import agent.apps.call_sessions.models
import agent.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biography', models.FileField(blank=True, null=True, storage=agent.storage_backends.PrivateMediaStorage(), upload_to=agent.apps.call_sessions.models.biography_file_upload_to_path)),
            ],
            options={
                'verbose_name': 'Biography',
                'verbose_name_plural': 'Biographies',
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, storage=agent.storage_backends.PrivateMediaStorage(), upload_to=agent.apps.call_sessions.models.callsession_audio_file_upload_to_path)),
                ('summary', models.TextField(blank=True, null=True)),
                ('analyzer_summary', models.TextField(blank=True, null=True)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], max_length=120)),
            ],
            options={
                'verbose_name': 'Call Session',
                'verbose_name_plural': 'Call Sessions',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('postfix', models.TextField(blank=True, null=True)),
                ('save_time', models.DateTimeField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, storage=agent.storage_backends.PrivateMediaStorage(), upload_to=agent.apps.call_sessions.models.conversation_audio_file_upload_to_path)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationTopicSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('audio', models.FileField(blank=True, null=True, storage=agent.storage_backends.PrivateMediaStorage(), upload_to=agent.apps.call_sessions.models.conversation_summary_audio_file_upload_to_path)),
                ('share_link', models.CharField(blank=True, default='', max_length=55, null=True)),
            ],
            options={
                'verbose_name': 'Conversation Topic Summary',
                'verbose_name_plural': 'Conversation Topic Summaries',
            },
        ),
        migrations.CreateModel(
            name='DigitalPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digital_persona', models.FileField(blank=True, null=True, storage=agent.storage_backends.PrivateMediaStorage(), upload_to=agent.apps.call_sessions.models.digital_persona_file_upload_to_path)),
            ],
            options={
                'verbose_name': 'Digital Persona',
                'verbose_name_plural': 'Digital Personas',
            },
        ),
        migrations.CreateModel(
            name='PostfixPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('prompt_type', models.CharField(choices=[('first_topic', 'First Topic'), ('next_topic', 'Next Topic'), ('end_topic', 'End Topic'), ('postfix_template', 'Postfix Template')], max_length=120)),
                ('category', models.CharField(choices=[('default', 'Default'), ('trial', 'Trial'), ('notrivia', 'No Trivia')], default='default', max_length=120)),
            ],
            options={
                'verbose_name': 'Postfix Prompt',
                'verbose_name_plural': 'Postfix Prompts',
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('key', models.CharField(blank=True, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shared Link',
                'verbose_name_plural': 'Shared Links',
            },
        ),
        migrations.CreateModel(
            name='SummarySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('max_tokens', models.IntegerField(default=250)),
                ('prompt', models.TextField()),
                ('summary_type', models.CharField(choices=[('session_summary', 'Session Summary'), ('conversation_summary', 'Conversation Summary'), ('analyze_session_summary', 'Analyze Session Summary')], max_length=120)),
            ],
            options={
                'verbose_name': 'Summary Settings',
                'verbose_name_plural': 'Summary Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('introduction', 'Introduction'), ('default', 'Default'), ('trial', 'Trial'), ('notrivia', 'No Trivia')], max_length=120)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=120)),
            ],
            options={
                'verbose_name': 'System Prompt',
                'verbose_name_plural': 'System Prompts',
            },
        ),
        migrations.CreateModel(
            name='TrialCallSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('audio', models.FileField(blank=True, null=True, storage=agent.storage_backends.PrivateMediaStorage(), upload_to=agent.apps.call_sessions.models.trial_callsession_audio_file_upload_to_path)),
            ],
            options={
                'verbose_name': 'Trial Call Session',
                'verbose_name_plural': 'Trial Call Sessions',
            },
        ),
        migrations.CreateModel(
            name='TrialConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('postfix', models.TextField(blank=True, null=True)),
                ('save_time', models.DateTimeField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, storage=agent.storage_backends.PrivateMediaStorage(), upload_to=agent.apps.call_sessions.models.trial_conversation_audio_file_upload_to_path)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='call_sessions.trialcallsession')),
            ],
        ),
    ]
