# Generated by Django 3.1.6 on 2024-05-10 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('questions', '0001_initial'),
        ('call_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialconversation',
            name='system_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_system_conversations', to='questions.systemquestion'),
        ),
        migrations.AddField(
            model_name='trialcallsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_call_session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='topic_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_shared_links', to='call_sessions.conversationtopicsummary'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitalpersona',
            name='receiver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_persona', to='accounts.giftreceiver'),
        ),
        migrations.AddField(
            model_name='conversationtopicsummary',
            name='personal_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_topic_summaries', to='questions.personalquestion'),
        ),
        migrations.AddField(
            model_name='conversationtopicsummary',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_summaries', to='accounts.giftreceiver'),
        ),
        migrations.AddField(
            model_name='conversationtopicsummary',
            name='system_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_topic_summaries', to='questions.systemquestion'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='call_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='call_sessions.callsession'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='personal_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_conversations', to='questions.personalquestion'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='system_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_conversations', to='questions.systemquestion'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_session', to='accounts.giftreceiver'),
        ),
        migrations.AddField(
            model_name='biography',
            name='receiver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biography', to='accounts.giftreceiver'),
        ),
    ]
