# Generated by Django 3.1.6 on 2024-05-13 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('call_sessions', '0002_auto_20240510_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsession',
            name='receiver',
        ),
        migrations.AddField(
            model_name='callsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='call_session', to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
