# Generated by Django 3.1.6 on 2024-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_sessions', '0004_auto_20240517_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='category',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('default', 'Default'), ('trial', 'Trial'), ('notrivia', 'No Trivia'), ('apex', 'Apex')], max_length=120),
        ),
    ]
